// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mikroERP.API.Data;

namespace mikroERP.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20190402145547_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854");

            modelBuilder.Entity("mikroERP.API.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("LocationId");

                    b.Property<string>("NameOfDepartment");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LocationId = 1,
                            NameOfDepartment = "Management"
                        },
                        new
                        {
                            Id = 2,
                            LocationId = 2,
                            NameOfDepartment = "Logistics Department"
                        },
                        new
                        {
                            Id = 3,
                            LocationId = 6,
                            NameOfDepartment = "Administration Department"
                        },
                        new
                        {
                            Id = 4,
                            LocationId = 7,
                            NameOfDepartment = "Marketing department"
                        });
                });

            modelBuilder.Entity("mikroERP.API.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<DateTime>("DayOfEmployment");

                    b.Property<int?>("DepartmentId");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<int>("Phone");

                    b.Property<string>("Sex");

                    b.Property<int?>("TransportId");

                    b.Property<double>("Wages");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("TransportId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(1994, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayOfEmployment = new DateTime(2017, 4, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 2,
                            Email = "adam.kowalski@xx.pl",
                            FirstName = "Adam",
                            LastName = "Kowalski",
                            Phone = 123456789,
                            Sex = "M",
                            TransportId = 1,
                            Wages = 5000.0
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(1974, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayOfEmployment = new DateTime(2007, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 3,
                            Email = "ewa.lampa@xx.pl",
                            FirstName = "Ewa",
                            LastName = "Lampa",
                            Phone = 123789456,
                            Sex = "F",
                            TransportId = 6,
                            Wages = 3000.0
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateTime(1987, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayOfEmployment = new DateTime(2011, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 4,
                            Email = "kacper.stol@xx.pl",
                            FirstName = "Kacper",
                            LastName = "Stół",
                            Phone = 345126789,
                            Sex = "M",
                            TransportId = 4,
                            Wages = 5000.0
                        },
                        new
                        {
                            Id = 4,
                            DateOfBirth = new DateTime(1995, 6, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayOfEmployment = new DateTime(2014, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 4,
                            Email = "joanna.poduszka@xx.pl",
                            FirstName = "Joanna",
                            LastName = "Poduszka",
                            Phone = 123678945,
                            Sex = "F",
                            TransportId = 5,
                            Wages = 4000.0
                        },
                        new
                        {
                            Id = 5,
                            DateOfBirth = new DateTime(1997, 4, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayOfEmployment = new DateTime(2015, 9, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 2,
                            Email = "wojtek.grzyb@xx.pl",
                            FirstName = "Wojtek",
                            LastName = "Grzyb",
                            Phone = 127893456,
                            Sex = "M",
                            TransportId = 5,
                            Wages = 3500.0
                        },
                        new
                        {
                            Id = 6,
                            DateOfBirth = new DateTime(1993, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayOfEmployment = new DateTime(2010, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 1,
                            Email = "wiktor.kalafior@xx.pl",
                            FirstName = "Wiktor",
                            LastName = "Kalafior",
                            Phone = 678912345,
                            Sex = "M",
                            TransportId = 3,
                            Wages = 7500.0
                        },
                        new
                        {
                            Id = 7,
                            DateOfBirth = new DateTime(1986, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayOfEmployment = new DateTime(2012, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 4,
                            Email = "maciej.cerata@xx.pl",
                            FirstName = "Maciej",
                            LastName = "Cerata",
                            Phone = 123945678,
                            Sex = "M",
                            TransportId = 2,
                            Wages = 6000.0
                        },
                        new
                        {
                            Id = 8,
                            DateOfBirth = new DateTime(1997, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayOfEmployment = new DateTime(2018, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 2,
                            Email = "marcin.brokul@xx.pl",
                            FirstName = "Marcin",
                            LastName = "Brokuł",
                            Phone = 456123789,
                            Sex = "M",
                            TransportId = 6,
                            Wages = 5000.0
                        },
                        new
                        {
                            Id = 9,
                            DateOfBirth = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayOfEmployment = new DateTime(2019, 1, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 4,
                            Email = "martyna.pudelko@xx.pl",
                            FirstName = "Martyna",
                            LastName = "Pudełko",
                            Phone = 567891234,
                            Sex = "F",
                            TransportId = 1,
                            Wages = 5500.0
                        },
                        new
                        {
                            Id = 10,
                            DateOfBirth = new DateTime(1989, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayOfEmployment = new DateTime(2015, 12, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 3,
                            Email = "agata.kot@xx.pl",
                            FirstName = "Agata",
                            LastName = "Kot",
                            Phone = 156723489,
                            Sex = "F",
                            TransportId = 1,
                            Wages = 3300.0
                        },
                        new
                        {
                            Id = 11,
                            DateOfBirth = new DateTime(1989, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayOfEmployment = new DateTime(2010, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 4,
                            Email = "karolina.butelka@xx.pl",
                            FirstName = "Karolina",
                            LastName = "Butelka",
                            Phone = 234516789,
                            Sex = "F",
                            TransportId = 1,
                            Wages = 5300.0
                        },
                        new
                        {
                            Id = 12,
                            DateOfBirth = new DateTime(1976, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayOfEmployment = new DateTime(2009, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 2,
                            Email = "natalia.lisc@xx.pl",
                            FirstName = "Natalia",
                            LastName = "Liść",
                            Phone = 123784569,
                            Sex = "F",
                            TransportId = 1,
                            Wages = 5400.0
                        },
                        new
                        {
                            Id = 13,
                            DateOfBirth = new DateTime(1970, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayOfEmployment = new DateTime(2018, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 3,
                            Email = "wioletta.popiol@xx.pl",
                            FirstName = "Wioletta",
                            LastName = "Popiół",
                            Phone = 456781239,
                            Sex = "F",
                            TransportId = 1,
                            Wages = 4400.0
                        },
                        new
                        {
                            Id = 14,
                            DateOfBirth = new DateTime(1984, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayOfEmployment = new DateTime(2018, 7, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 4,
                            Email = "janusz.smith@xx.pl",
                            FirstName = "Janusz",
                            LastName = "Smith",
                            Phone = 123458967,
                            Sex = "M",
                            TransportId = 1,
                            Wages = 4100.0
                        },
                        new
                        {
                            Id = 15,
                            DateOfBirth = new DateTime(1982, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayOfEmployment = new DateTime(2019, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 2,
                            Email = "pawel.mcree@xx.pl",
                            FirstName = "Paweł",
                            LastName = "McRee",
                            Phone = 678123459,
                            Sex = "M",
                            TransportId = 4,
                            Wages = 7400.0
                        },
                        new
                        {
                            Id = 16,
                            DateOfBirth = new DateTime(1968, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayOfEmployment = new DateTime(2007, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 1,
                            Email = "jonnathan.joestar@xx.pl",
                            FirstName = "Jonnathan",
                            LastName = "Joestar",
                            Phone = 456789123,
                            Sex = "M",
                            TransportId = 1,
                            Wages = 10000.0
                        },
                        new
                        {
                            Id = 17,
                            DateOfBirth = new DateTime(1970, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayOfEmployment = new DateTime(2013, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 1,
                            Email = "soap.price@xx.pl",
                            FirstName = "Soap",
                            LastName = "Price",
                            Phone = 127345689,
                            Sex = "M",
                            TransportId = 1,
                            Wages = 8000.0
                        },
                        new
                        {
                            Id = 18,
                            DateOfBirth = new DateTime(1984, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayOfEmployment = new DateTime(2017, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 2,
                            Email = "anna.migawka@xx.pl",
                            FirstName = "Anna",
                            LastName = "Migawka",
                            Phone = 456123789,
                            Sex = "F",
                            TransportId = 3,
                            Wages = 2700.0
                        },
                        new
                        {
                            Id = 19,
                            DateOfBirth = new DateTime(1988, 12, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayOfEmployment = new DateTime(2014, 7, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 2,
                            Email = "klaudia.pass@xx.pl",
                            FirstName = "Klaudia",
                            LastName = "Pass",
                            Phone = 126789345,
                            Sex = "F",
                            TransportId = 2,
                            Wages = 3400.0
                        },
                        new
                        {
                            Id = 20,
                            DateOfBirth = new DateTime(1988, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayOfEmployment = new DateTime(2015, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 3,
                            Email = "krzysztof.krzysztof@xx.pl",
                            FirstName = "Krzysztof",
                            LastName = "Mastuczak",
                            Phone = 234516789,
                            Sex = "M",
                            TransportId = 1,
                            Wages = 5800.0
                        });
                });

            modelBuilder.Entity("mikroERP.API.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("FloorNr");

                    b.Property<int>("RoomNr");

                    b.HasKey("Id");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FloorNr = 1,
                            RoomNr = 101
                        },
                        new
                        {
                            Id = 2,
                            FloorNr = 1,
                            RoomNr = 102
                        },
                        new
                        {
                            Id = 3,
                            FloorNr = 1,
                            RoomNr = 103
                        },
                        new
                        {
                            Id = 4,
                            FloorNr = 1,
                            RoomNr = 104
                        },
                        new
                        {
                            Id = 5,
                            FloorNr = 1,
                            RoomNr = 105
                        },
                        new
                        {
                            Id = 6,
                            FloorNr = 2,
                            RoomNr = 201
                        },
                        new
                        {
                            Id = 7,
                            FloorNr = 2,
                            RoomNr = 202
                        },
                        new
                        {
                            Id = 8,
                            FloorNr = 2,
                            RoomNr = 203
                        },
                        new
                        {
                            Id = 9,
                            FloorNr = 2,
                            RoomNr = 204
                        },
                        new
                        {
                            Id = 10,
                            FloorNr = 2,
                            RoomNr = 205
                        });
                });

            modelBuilder.Entity("mikroERP.API.Models.Transport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("NameOfTransport");

                    b.HasKey("Id");

                    b.ToTable("Transports");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NameOfTransport = "Car"
                        },
                        new
                        {
                            Id = 2,
                            NameOfTransport = "Walk"
                        },
                        new
                        {
                            Id = 3,
                            NameOfTransport = "Bike"
                        },
                        new
                        {
                            Id = 4,
                            NameOfTransport = "Public Transport"
                        },
                        new
                        {
                            Id = 5,
                            NameOfTransport = "Train"
                        },
                        new
                        {
                            Id = 6,
                            NameOfTransport = "Other"
                        });
                });

            modelBuilder.Entity("mikroERP.API.Models.Department", b =>
                {
                    b.HasOne("mikroERP.API.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId");
                });

            modelBuilder.Entity("mikroERP.API.Models.Employee", b =>
                {
                    b.HasOne("mikroERP.API.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId");

                    b.HasOne("mikroERP.API.Models.Transport", "Transport")
                        .WithMany()
                        .HasForeignKey("TransportId");
                });
#pragma warning restore 612, 618
        }
    }
}
